### PR TITLE
MAINT: update GitHub Actions

### PR DESCRIPTION
**Pull request by mmcky**
This PR

- [x] updates GitHub Actions to use GitHub runners
- [x] updates to the latest releases of workflow packages
- [x] review `netlify` setup
- [x] update credentials

### CODE REVIEW

**Comment by mmcky** [comment]
- [x] fix `pdf` builds via `LaTeX`

LaTeX doesn't like the `&` character used in the title. **Update:** I will fix this using `and` for the time being and will open an issue for `sphinx-jupyterbook-latex`

**Comment by mmcky** [comment]
- [x] update `svd_intro`

**Comment by mmcky** [comment]
@HumphreyYang I have this building locally but I wait for advise on #3 in case you want to run a final round of your migration script.

**Comment by HumphreyYang** [comment]
Many thanks @mmcky,

I think Tom is still doing edits across lectures. Should we wait and pull them all before we go live?

**Comment by mmcky** [comment]
@HumphreyYang if it is easy to update the lecture sources I would like to do an update today if possible.

**Comment by mmcky** [comment]
> @HumphreyYang if it is easy to update the lecture sources I would like to do an update today if possible.

If we can just ensure the lecture sources are up to date that would be great. Please don't change `github actions` etc.

**Pull request merged**
